# Data settings
scenario: motorway
simulation_name: incident_large
form: independent # incident_only, independent, graph
num_nodes : 147

# Logger setttings
wandb_project: debug
wandb_name: test_1
debug: True

# Training settings
gpu: 1
epochs: 2000
batch_size: 1000
infer_lr: False
learning_rate: 0.0003
full_loss: True
bce_pos_weight:  25.5191 # full: 25.5191, ie: 02502
dropout: 0.5
random_seed: 42 


# General model settings
model: attention
timeseries_in_size: 20 
n_timesteps: 10
fc_hidden_size: 16 
info_in_size: 3
network_in_size: 13
out_size: 4

# MLP settings
mlp_in_size: 200
mlp_hidden_size: 30

# TCN settings
num_channels: [20, 20, 10]
cnn_in_size: 20
kernel_size: 3
tcn_emb_size: 100

# LSTM hidden size
rnn_hidden_size: 32 

# Attention settings
attention_num_heads: 1

# DCRNN settings
max_diffusion_step: 2
filter_type: random_walk
use_gc_ru: True
use_gc_c: True
use_curriculum_learning: False
cl_decay_steps: None
num_layers: 2
activation: linear

AD_path: /home/manity/Quick_adap/quick_adap_to_incidents/Simulation_scenarios/motorway/Results/incident3/link_AD_matrix.npy

