# Data settings
scenario: motorway
simulation_name: incident_large
form: graph # incident_only, independent, graph
transform: scalenormalize
transform_network_info: True
num_nodes : 147
spatial_test: False
subset_size: 
min_impact_threshold: 
sliding_window_steps: 5

# Logger setttings
wandb_project: sliding_window_sim_nri
wandb_name: nri_5
debug: False

# Training settings
gpu: 1
epochs: 300
batch_size: 100
infer_lr: False
learning_rate: 0.00006
loss_type: nri_loss
full_loss: True
bce_pos_weight: 2 #25.5191 # full: 25.5191, ie: 02502
dropout: 0.5
random_seed: 41 
lightning_precision: 16

results_dir: /home/manity/Quick_adap/quick_adap_to_incidents/saved_models/sliding_window_experiment/nri_5

# Model settings
model: nri
timeseries_in_size: 20
rnn_hidden_size: 64
fc_hidden_size: 64
network_in_size: 13
info_in_size: 3
n_timesteps: 10
limited_network_info: False


# NRI specific settings
AD_path: /home/manity/Quick_adap/quick_adap_to_incidents/Simulation_scenarios/motorway/Results/incident3/link_AD_matrix.npy
nri_n_hid: 64
nri_log_prior: 0.1

