# Data settings
scenario: motorway
simulation_name: incident_large
form: independent # incident_only, independent, graph
num_nodes : 147

# Logger setttings
wandb_project: baseline_comp_res
wandb_name: tcn
debug: False

# Training settings
gpu: 1
epochs: 300
batch_size: 1000
infer_lr: False
learning_rate: 0.0003
full_loss: True
bce_pos_weight: 25.5191 # full: 25.5191, ie: 02502 
dropout: 0.5
random_seed: 44
checkpoint_path: /home/manity/Quick_adap/quick_adap_to_incidents/saved_models/baseline_comp/tcn/44.ckpt

result_dir: /home/manity/Quick_adap/quick_adap_to_incidents/saved_models/baseline_comp/tcn/


# General model settings
model: tcn
timeseries_in_size: 20 
n_timesteps: 10
fc_hidden_size: 16 
info_in_size: 3
network_in_size: 13
out_size: 4

# TCN settings
num_channels: [20, 20, 10]
cnn_in_size: 20
kernel_size: 3
tcn_emb_size: 100