# Data settings
scenario: motorway
simulation_name: incident_large
form: graph # incident_only, independent, graph
num_nodes : 147

# Logger setttings
wandb_project: informed_baseline_comp
wandb_name: informed_dcrnn
debug: False

# Training settings
gpu: 0
epochs: 300
batch_size: 600
infer_lr: False
learning_rate: 0.0003
full_loss: True
bce_pos_weight: 25.5191 # full: 25.5191, ie: 02502
dropout: 0.5
random_seed: 44
checkpoint_path: /home/manity/Quick_adap/quick_adap_to_incidents/saved_models/informed_baseline_comp/inf_dcrnn/44.ckpt

result_dir: /home/manity/Quick_adap/quick_adap_to_incidents/saved_models/informed_baseline_comp/inf_dcrnn/

# Model settings
model: informed_gnn
timeseries_in_size: 20 
n_timesteps: 10
fc_hidden_size: 16 
info_in_size: 3
network_in_size: 13
out_size: 4

# Rose settings
max_diffusion_step: 2
filter_type: random_walk
use_gc_ru: True
use_gc_c: True
use_curriculum_learning: False
cl_decay_steps: None
num_layers: 2
activation: linear
rnn_hidden_size: 16 

AD_path: /home/manity/Quick_adap/quick_adap_to_incidents/Simulation_scenarios/motorway/Results/incident3/link_AD_matrix.npy

