# Data settings
scenario: pems
simulation_name: pems_data
form: graph # incident_only, independent, graph
transform: scalenormalize
transform_network_info: True
num_nodes : 215
spatial_test: False
subset_size: 150
min_impact_threshold: 
limited_network_info: False

# Logger setttings
wandb_project: dataset_size_exp_rw
wandb_name: inf_dcrnn_150
debug: False

# Training settings
gpu: 1
epochs: 600
batch_size: 400
infer_lr: False
learning_rate: 0.0003
loss_type: focal_loss
full_loss: True
bce_pos_weight: 16 # Somewhat around half  #25.28 # full: 25.5191, ie: 02502
dropout: 0.5
random_seed: 42 
lightning_precision: 32

results_dir: /home/manity/Quick_adap/quick_adap_to_incidents/saved_models/subset_exp_rw/inf_dcrnn_150

# Model settings
model: informed_gnn_v3
timeseries_in_size: 7
n_timesteps: 12
fc_hidden_size: 64
info_in_size: 3
network_in_size: 1
out_size: 4

# Rose settings
max_diffusion_step: 1
filter_type: random_walk
use_gc_ru: True
use_gc_c: True
use_curriculum_learning: False
cl_decay_steps: None
num_layers: 1
activation: linear
rnn_hidden_size: 128 

AD_path: /home/manity/Quick_adap/quick_adap_to_incidents/pems_data/PEMS_d7_adj.npy
