# Data settings
scenario: motorway
simulation_name: incident_large
form: independent # incident_only, independent, graph
transform: scalenormalize
transform_network_info: True
num_nodes : 147
spatial_test: True
subset_size: 
min_impact_threshold: 

# Logger setttings
wandb_project: uninformed_spatial_comp
wandb_name: attention
debug: False

# Training settings
gpu: 1
epochs: 300
batch_size: 1000
infer_lr: False
learning_rate: 0.0003
loss_type: focal_loss
full_loss: True
bce_pos_weight: 25.5 # full: 25.5191, ie: 02502
dropout: 0.5
random_seed: 42 
lightning_precision: 32

results_dir: /home/manity/Quick_adap/quick_adap_to_incidents/saved_models/uninformed_spatial_comp/attention

# General model settings
model: attention
timeseries_in_size: 20 
n_timesteps: 10
fc_hidden_size: 16 
info_in_size: 3
network_in_size: 13
out_size: 4

# LSTM hidden size
rnn_hidden_size: 32 

# Attention settings
attention_num_heads: 1
