# Data settings
scenario: motorway
simulation_name: incident_large
form: independent
transform: scalenormalize
transform_network_info: True
num_nodes: 147
spatial_test: True

# Logger setttings
wandb_project: informed_baseline_comp3
wandb_name: informed_attention
debug: False

# Training settings
gpu: 1
epochs: 600
batch_size: 1000
infer_lr: False
learning_rate: 0.0003
loss_type: full
bce_pos_weight: 25.5191 # full: 25.5191, ie: 02502
dropout: 0.5
random_seed: 42
checkpoint_path: /home/manity/Quick_adap/quick_adap_to_incidents/saved_models/informed_baseline_comp2/inf_attention/41.ckpt

result_dir: /home/manity/Quick_adap/quick_adap_to_incidents/saved_models/informed_baseline_comp2/inf_attention/

# General Model settings
model: informed_attention
timeseries_in_size: 20 
n_timesteps: 10
fc_hidden_size: 16 
info_in_size: 3
network_info_size: None
out_size: 4

# LSTM settings
rnn_hidden_size: 32 

# Attention settings
attention_num_heads: 1