# Data settings
scenario: motorway
simulation_name: incident3
form: independent

# Logger setttings
wandb_project: full_network_full_loss2
wandb_name: informed_lstm_1
debug: False

# Training settings
gpu: 0
epochs: 2000
batch_size: 1000
infer_lr: True
full_loss: True
bce_pos_weight: 22.5178 # full: 22.5178 IE: 0.254

# Model settings
model: informed_lstm
timeseries_in_size: 20 
rnn_hidden_size: 32 
fc_hidden_size: 16 
info_in_size: 3
network_info_size: None