# Data settings
scenario: motorway
simulation_name: incident3
form: independent

# Logger setttings
wandb_project: full_network_full_loss4
wandb_name: lstm
debug: False

# Training settings
gpu: 0
epochs: 1000
batch_size: 1000
infer_lr: False
learning_rate: 0.0003
random_seed: 42
full_loss: True
bce_pos_weight: 22.5178 # full: 22.5178 IE: 0.254

# Model settings
model: lstm
timeseries_in_size: 20 
rnn_hidden_size: 32 
fc_hidden_size: 16 
network_info_size: None